CREATE TABLE PAYMENTS(
  order_id INT PRIMARY KEY ,
  pay_type VARCHAR (255) NOT NULL ,
  amount VARCHAR (255) NOT NULL ,
  time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
  FOREIGN KEY (order_id) REFERENCES ORDERS(id)
);